### ISSUE TITLE
Task:  get 5-10 fixture moab objects that can be put in a public git repo?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation2017#32]
@blalbrit ?

**Comment by blalbrit** [comment]
hrm. I hadn't checked rights on those objects, thinking we were using them internally. If you would like a set that could be made public, I can provide them. Want to turn this ticket into a task to do just that?

**Comment by ndushay** [comment]
closing this ticket in favor of sul-dlss/preservation_core_catalog/issues/7
